# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GithubHosts

on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 */2 * * *'
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements ]; then pip install -r requirements; fi
        
    - name: update hosts
      run: sh Hosts.sh && sh EpicHosts.sh && sh GithubHosts.sh
    - name: commit
      id: commit
      run: |
        git config --global user.email c13340908272@outlook.com
        git config --global user.name action_bot
        git add .
        git commit -m "update hosts"
      continue-on-error: true
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    # 同步代码到gitee；
    - name: Mirror the GithubHosts repos to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/JohyC
        dst: gitee/yuchi-shentang
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        force_update: true
        static_list: GithubHosts

    # 传送hosts文件到私人服务器；解决gitee违规问题；
    - name: put hosts to private
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'GithubHosts'
        server: 'suni.cf'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        local_path: './*.txt'
        remote_path: '/upload'
        args: '-o ConnectTimeout=15'
        
    # 删除无用 workflow runs;
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 0.1
        keep_minimum_runs: 1
        
